// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NoteService handles business logic for note operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../pkg/model/models.js";

/**
 * Create creates a new note after validating that the content is not empty.
 */
export function Create(input: model$0.NoteCreateInput): $CancellablePromise<model$0.Note | null> {
    return $Call.ByID(942669958, input);
}

/**
 * Delete removes a note by its ID.
 */
export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(4088511533, id);
}

/**
 * Get returns a single note by its ID.
 */
export function Get(id: number): $CancellablePromise<model$0.Note | null> {
    return $Call.ByID(708629374, id);
}

/**
 * List returns all notes ordered by most recently updated.
 */
export function List(): $CancellablePromise<model$0.Note[] | null> {
    return $Call.ByID(3884133902);
}

/**
 * Search finds notes whose title or content match the query string.
 * An empty query returns an empty slice without hitting the database.
 */
export function Search(query: string): $CancellablePromise<model$0.Note[] | null> {
    return $Call.ByID(127761658, query);
}

/**
 * Update modifies an existing note with the provided fields.
 */
export function Update(id: number, input: model$0.NoteUpdateInput): $CancellablePromise<model$0.Note | null> {
    return $Call.ByID(4220013515, id, input);
}
