// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TodoService handles business logic for todo operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../pkg/model/models.js";

/**
 * Create creates a new todo after validating that the title is not empty.
 */
export function Create(input: model$0.TodoCreateInput): $CancellablePromise<model$0.Todo | null> {
    return $Call.ByID(3583200614, input);
}

/**
 * Delete removes a todo by its ID.
 */
export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(4240417293, id);
}

/**
 * Get returns a single todo by its ID.
 */
export function Get(id: number): $CancellablePromise<model$0.Todo | null> {
    return $Call.ByID(2778292190, id);
}

/**
 * List returns todos matching the optional filter criteria.
 */
export function List(filter: model$0.TodoFilter | null): $CancellablePromise<model$0.Todo[] | null> {
    return $Call.ByID(3506783982, filter);
}

/**
 * Search finds todos whose title or description match the query string.
 * An empty query returns an empty slice without hitting the database.
 */
export function Search(query: string): $CancellablePromise<model$0.Todo[] | null> {
    return $Call.ByID(3127742170, query);
}

/**
 * Update modifies an existing todo with the provided fields.
 */
export function Update(id: number, input: model$0.TodoUpdateInput): $CancellablePromise<model$0.Todo | null> {
    return $Call.ByID(2182592939, id, input);
}
