// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Note represents a free-form text note with optional tags.
 */
export interface Note {
    /**
     * unique database identifier.
     */
    "id": number;

    /**
     * short title of the note.
     */
    "title": string;

    /**
     * full body content of the note.
     */
    "content": string;

    /**
     * associated tags for categorization.
     */
    "tags": Tag[] | null;

    /**
     * creation timestamp in ISO-8601 format.
     */
    "createdAt": string;

    /**
     * last modification timestamp in ISO-8601 format.
     */
    "updatedAt": string;
}

/**
 * NoteCreateInput carries the fields required to create a new note.
 */
export interface NoteCreateInput {
    /**
     * title of the new note.
     */
    "title": string;

    /**
     * body content (required).
     */
    "content": string;

    /**
     * tag names to associate with the note.
     */
    "tagNames": string[] | null;
}

/**
 * NoteUpdateInput carries partial fields for updating an existing note.
 * Only non-nil fields are applied during the update.
 */
export interface NoteUpdateInput {
    /**
     * new title value.
     */
    "title"?: string | null;

    /**
     * new body content.
     */
    "content"?: string | null;

    /**
     * replaces existing tags if non-empty.
     */
    "tagNames"?: string[] | null;
}

/**
 * Tag represents a named label that can be attached to todos and notes.
 */
export interface Tag {
    /**
     * unique database identifier.
     */
    "id": number;

    /**
     * human-readable tag name (case-insensitive).
     */
    "name": string;
}

/**
 * Todo represents a task item with status, priority, and optional tags.
 */
export interface Todo {
    /**
     * unique database identifier.
     */
    "id": number;

    /**
     * short title of the todo.
     */
    "title": string;

    /**
     * detailed description text.
     */
    "description": string;

    /**
     * one of pending, in_progress, completed.
     */
    "status": string;

    /**
     * one of low, medium, high, urgent.
     */
    "priority": string;

    /**
     * optional due date as ISO-8601 string.
     */
    "dueDate"?: string | null;

    /**
     * timestamp when status became completed.
     */
    "completedAt"?: string | null;

    /**
     * associated tags for categorization.
     */
    "tags": Tag[] | null;

    /**
     * creation timestamp in ISO-8601 format.
     */
    "createdAt": string;

    /**
     * last modification timestamp in ISO-8601 format.
     */
    "updatedAt": string;
}

/**
 * TodoCreateInput carries the fields required to create a new todo.
 */
export interface TodoCreateInput {
    /**
     * title of the new todo (required).
     */
    "title": string;

    /**
     * optional description text.
     */
    "description": string;

    /**
     * priority level; defaults to medium if empty.
     */
    "priority": string;

    /**
     * optional due date as ISO-8601 string.
     */
    "dueDate"?: string | null;

    /**
     * tag names to associate with the todo.
     */
    "tagNames": string[] | null;
}

/**
 * TodoFilter specifies optional criteria for filtering todo lists.
 */
export interface TodoFilter {
    /**
     * filter by status value.
     */
    "status"?: string | null;

    /**
     * filter by priority level.
     */
    "priority"?: string | null;

    /**
     * filter by associated tag name (case-insensitive).
     */
    "tagName"?: string | null;
}

/**
 * TodoUpdateInput carries partial fields for updating an existing todo.
 * Only non-nil fields are applied during the update.
 */
export interface TodoUpdateInput {
    /**
     * new title value.
     */
    "title"?: string | null;

    /**
     * new description text.
     */
    "description"?: string | null;

    /**
     * new status value.
     */
    "status"?: string | null;

    /**
     * new priority level.
     */
    "priority"?: string | null;

    /**
     * new due date as ISO-8601 string.
     */
    "dueDate"?: string | null;

    /**
     * replaces existing tags if non-empty.
     */
    "tagNames"?: string[] | null;
}
